### ISSUE TITLE
Set consistent FPCA seed during registration iterations

### ISSUE THREAD

**Issue by eimcdonnell** [julia-wrobel/registr#13]
Within `register_fpca()`, each iteration calls the functions `fpca_gauss()` or `bfpca()` with seed `1988 + iter`. Setting a consistent seed across iterations (i.e. `1988`) will remove a source of random variability by initializing parameters with consistent values inside those functions.

**Comment by bauer-alex** [comment]
Can be closed since the change is apparently already implemented on the master.
