### ISSUE TITLE
Registration to user-specified template function

### ISSUE THREAD

**Issue by bauer-alex** [julia-wrobel/registr#24]
**Problem**
As initial step in `register_fpca()` all curves are registered to the overall mean of all curves. In some settings (e.g. in our seismic setting where both the amount of incompleteness and amplitude sizes structurally vary over space) the mean curve is no good choice for an initial template.

**Solution**
Include a new argument `Y_template` in `registr()` and `register_fpca()`. The template function is then defined as the mean curve calculated over `Y_template`. The argument should have the same structure as the data `Y` itself. In this way the user has two options:
1. Define `Y_template` as a subset of `Y`, s.t. the template function is defined as the mean curve over this chosen subset of curves.
2. Manually define / calculate some template function before calling the registration function, and pass it to the function as `Y_template`.

**Comment by julia-wrobel** [comment]
This is nice functionality to have- will you add an example to the vignette or package documentation that shows how to pass a user-defined template?

**Comment by bauer-alex** [comment]
Yeah, I'll also add an example to the main vignette.

**Comment by julia-wrobel** [comment]
Awesome!

**Comment by bauer-alex** [comment]
done. See the main vignette on the master.
