### ISSUE TITLE
Add families exponential and poisson

### ISSUE THREAD

**Issue by bauer-alex** [julia-wrobel/registr#28]
Add both the exponential distribution and the poisson distribution as new families.
Also highlight it in the documentation that the package then supports many different exponential families.

**Comment by bauer-alex** [comment]
Apparently the exponential distribution is implemented a bit weirdly for the use with `glm()`. According to [this answer](https://grokbase.com/t/r/r-help/036amhmgd1/r-fitting-data-to-exponential-distribution-with-glm) exponential distribution data can be modelled using the gamma family (since exponential is a special case of gamma) and then setting the dispersion parameter to 1 when applying `summary.glm()` after the main model fit.
Since `gamm4` (for estimating our two-step GFPCA) also uses the base glm families and it's not directly clear to me how this handling of the dispersion parameter affects the method, I will for now drop the exponential family and only implement poisson.

**Comment by bauer-alex** [comment]
Ok, so also the implementation of the Poisson family is not without problems.
The problem is that for non-integer values the GFPCA estimation with `gamm4::gamm4()` is incredibly slow. For estimating either one single registration step or one single GFPCA step on integer data this wouldn't be problematic of course. But if multiple joint iterations with `register_fpca()` are performed the non-integer mean structure output of the very first GFPCA step would have to be analyzed in the following GFPCA steps. As far as I see it this would leave us with two options:
1. Hint the user that `register_fpca()` will simply be incredibly slow for poisson data.
2. Round the data before throwing it into `gamm4()` since the poisson model is really fast on integer data.

Both options don't really seem satisfactory to me. Option 1 because the runtimes on non-integer data are reaaaally slow, see below.
Accordingly, I for now will not implement the poisson family and keep this issue on hold.
@julia-wrobel We can also close the issue if you think that's best.

Some example runtimes of `gamm4()`:
```r
library(dplyr)   
library(registr) # version 1.2.1; for the example dataset
library(gamm4)   # version 0.2-6
library(mgcv)    # version 1.8-33; for gamma family

# use some random, strictly positive dataset
dat <- registr::growth_incomplete %>%
  mutate(value = abs(value) / 10 + 1)

system.time({ m1 <- gamm4::gamm4(value ~ s(index), data = dat, family = "gaussian") })
# -> Gaussian: 0.1 seconds
system.time({ m2 <- gamm4::gamm4(value ~ s(index), data = dat, family = mgcv::Tweedie(p = 2, link = "log")) })
# -> Gamma: 0.9 seconds
system.time({ m3 <- gamm4::gamm4(value ~ s(index), data = dat, family = "poisson") })
# -> Poisson (non-integer data): 153 seconds

dat_round <- dat %>% mutate(value = round(value))
system.time({ m4 <- gamm4::gamm4(value ~ s(index), data = dat_round, family = "poisson") })
# -> Poisson (integer data): 0.4 seconds
```

**Comment by julia-wrobel** [comment]
Sorry Alex, just getting around to this.   I think it's no big deal to drop the exponential distribution. It's too bad about the Poisson case, though. There are accelerometry examples where modeling as poisson is very useful.  In this case the data is actually integer valued (activity "counts" or "steps"). Can you implement solution 2 for Poisson? I agree it is not ideal, but still useful to have.  Solution 1 is way too slow.

**Comment by bauer-alex** [comment]
Solution 2 for the Poisson family is now implemented.
