### ISSUE TITLE
Registration bug when the domain doesn't start at zero

### ISSUE THREAD

**Issue by bauer-alex** [julia-wrobel/registr#9]
Regarding the pure registration step with `registr::registr`, the `constrOptim` based optimization warps to values outside the observed domain when the latter is not starting at value zero.

Example (based on the example in `?registr::registr`):
```
# simulate data with a domain starting at zero
Y <- simulate_unregistered_curves()
range(Y$index) # result: 0 1

# register these data
register_step <- registr(obj = NULL, Y = Y, Kt = 6, Kh = 3, family = "binomial", gradient = TRUE)
range(register_step$Y$tstar) # result: 0 1
range(register_step$Y$index) # result: 0 1
# -> everything fine

# create a second dataset with a domain not starting at zero
# (by simply adding some random shift)
Y2 <- Y
Y2$index <- Y2$index + 0.3
range(Y2$index) # result: 0.3 1.3

# register these data
register_step2 = registr(obj = NULL, Y = Y2, Kt = 6, Kh = 3, family = "binomial", gradient = TRUE)
range(register_step2$Y$tstar) # result: 0.3 1.3
range(register_step2$Y$index) # result: 0.3 1.6
# -> registered domain (index) is different from the observed domain (tstar)
```

My current guess is that this is caused by some bug in the constraint definition. Using `family = "gaussian"` also leads to the distorted domain.

**Comment by julia-wrobel** [comment]
Thanks Alex- I'll look into this tomorrow, pretty sure I know what's causing it.

**Comment by julia-wrobel** [comment]
Got to this much later than I thought I would, but just pushed a change that should resolve the issue. Thanks for pointing this out! Let me know if you find anything else.
